blog/urls.py
from django.contrib import admin
# from django.
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogcrud.urls',namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogcrud/urls.py
from django.urls import path
from blogcrud import views
app_name='blogcrud'

urlpatterns=[
    path('',views.landingview,name='landingpage'),
    path('list-of-blogs',views.list_blog,name='listblogs'),
    path('blog-detail/<int:blog_id>/',views.blog_detail,name='blogdetail'),
]

blogcrud/models.py
from django.db import models

# Create your models here.
class Aurthor(models.Model):
    name=models.CharField(max_length=100)
    age=models.IntegerField()
    address=models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Blogs(models.Model):
    author = models.ForeignKey(Aurthor,on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    date_created = models.DateTimeField()
    date_updated = models.DateTimeField(default=None)
    images = models.ImageField(default=None)
    content = models.TextField()

    def __str__(self):
        return self.title

blogcrud/views.py
from django.shortcuts import render
from .models import Blogs,Aurthor
# Create your views here.
def landingview(request):
    return render(request,'index.html')

def list_blog(request):
    blog_list=Blogs.objects.all()
    context = {
        'blog_list':blog_list,
    }
    return render(request,'bloglist.html',context)

def blog_detail(request,blog_id):
    get_blog=Blogs.objects.get(id=blog_id)
    context={
        'blogdetail':get_blog
    }
    return  render(request,'detailblog.html',context)

blogcrud/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg menubar1">
    <b><i>“The casual conversational tone of a blog is what makes it particularly dangerous”</i></b>
</nav>

{% block content %}

{% endblock %}



<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</html>

blogcrud/templates/bloglist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% include 'nav.html' %}
    <div class="container ">
        <div class="blog">
            <h1>
                <center>Blogs List</center>
            </h1>
        </div>
    </div>
    <br>
    {% for blog in blog_list %}
    <div class="container blog-list">
        <div class="row">
            <div class="col-md-4">
                <h4>{{ blog.title }}</h4>
                <h6><i>Author: {{blog.author}}</i></h6>
            </div>
            <div class="col-md-3">
                Created: {{ blog.date_created }}
            </div>
            <div class="col-md-3">
                Updated: {{ blog.date_updated }}
            </div>
            <div class="col-md-2">
                <button name="view" class="btn-view"><a href="{% url 'blog:blogdetail' blog.id %}">View Detail </a></button>
{#                <a href="{% url 'blogcrud:blogdetail' %}">View Detail </a>#}
            </div>
        </div>
    </div>
        <br>
    {% endfor %}
{% endblock %}

blogcrud/templates/detailblog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% include 'nav.html' %}
    <div class="container blog-detail">
    <p>Blog No: {{ blogdetail.id }}</p>
        <center> <h3>{{ blogdetail.title }}</h3><br>
    <img src="{{ blogdetail.images.url }}" height="500" width="100%"></center><br>
    <br>
    <b>Author:{{ blogdetail.author }}</b><br>
    <b>Date Created:{{ blogdetail.date_created }}</b><br>
        {% if blogdetail.date_updated %}
            <b>Last Update: {{ blogdetail.date_updated }}</b>
        {% endif %}
    <hr>
    <p>
        {{ blogdetail.content }}
    </p>
    </div>


{% endblock %}

blogcrud/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="background" style="background-image: url('{% static 'image/background.jpg' %}');">
     {% include 'nav.html' %}
        <section id="blog-wrap">
            <div class="container read-blog-wrapper">
                <div class="blog" style="height: 500px; ">
                    <h1>
                        <br>
                        <center><i>FEEL FREE TO CREATE BLOGS</i></center>
                    </h1>
                </div>
                {#        <div class="row">#}
                {#            <div class="col-md-4 blog-content">#}
                {#                <div class="inner-blog">#}
                {#                    <center><img src="{% static "image/background.jpg" %}" height="200px"></center>#}
                {#                    <hr>#}
                {#                </div>#}
                {#            </div>#}
                {#            <div class="col-md-4 blog-contet">#}
                {#                <div class="inner-blog">#}
                {#                </div>#}
                {#            </div>#}
                {#            <div class="col-md-4 blog-contet">#}
                {#                <div class="inner-blog">#}
                {#                </div>#}
                {#            </div>#}
                {#            <div class="col-md-4 blog-contet">#}
                {#                <div class="inner-blog">#}
                {#                </div>#}
                {#            </div>#}
                {#        </div>#}
            </div>
        </section>
    </div>
{% endblock %}

blogcrud/templates/nav.html
<section id="menu-bar">
    {#    <div class="navbar-menu-wrapper" style="background-image: url({% static 'image/cover.jpeg' %});">#}
    <div class="navbar-menu-wrapper">
        <nav class="navbar navbar-expand-lg menubar2">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto menu-adujst">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'blogcrud:landingpage' %}">Home <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blogcrud:listblogs' %}">Blog List</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</section>
 <hr>